.github/workflows/deploy.yml
.github/workflows/tests.yml
src/multipatch/README.md

Setup a push to the `public` branch on GitLab when the `main` branch is updated on GitHub.

Setup GitLab mirror

---

bin/indent

Be more explicit about clang-format version to allow people to have multiple versions of clang-format installed on their computer. Fixes #90

Be more explicit about clang-format version

---

.github/workflows/clean_up.yml
.github/workflows/draft_flags.yml
.github/workflows/flag_checks.yml
.github/workflows/gpu_tests.yml
.github/workflows/static_analyses.yml
.github/workflows/tests.yml

Minor improvements to the CI:
- Add a clean up workflow to take care of adding the `Ready to review` flag. This (should) ensure that this step is correctly triggered and takes into consideration both the CPU and GPU tests
- Remove unnecessary permissions (default are sufficient)
- Add missing `GH_TOKEN` to be able to correct flags
- Match SHA mentioned in commit to SHA used for GPU tests to make it easier to locate tests on GitLab
- Remove label workarounds in tests.yml that were designed for private forks but don't work (because private forks have to pay for CI)
- Remove concurrency limits

CI improvements

---

.github/actions/build_code/action.yml
.github/actions/run_tests/action.yml
.github/workflows/tests.yml

The toolchain is likely not used, there is a warning:
```
CMake Warning:
Manually-specified variables were not used by the project:
CMAKE_TOOLCHAIN
```

Fix CMAKE_TOOLCHAIN_FILE cmake variable

---

simulations/geometryRTheta/diocotron/diocotron.cpp
simulations/geometryRTheta/vortex_merger/vortex_merger.cpp
src/geometryRTheta/advection/bsl_advection_rp.hpp
src/geometryRTheta/interpolation/i_interpolator_2d_rp.hpp
src/geometryRTheta/interpolation/spline_interpolator_2d_rp.hpp
src/math_tools/math_tools.hpp
tests/geometryRTheta/2d_spline_interpolator/2d_spline_interpolator.cpp
tests/geometryRTheta/advection_2d_rp/advection_all_tests.cpp
tests/geometryRTheta/advection_2d_rp/advection_selected_test.cpp
tests/geometryRTheta/advection_field_rp/advection_field_gtest.cpp
tests/mapping/mapping_jacobian_matrix_coef.cpp
toolchains/v100.persee/debug_toolchain.cmake

Port the RTheta interpolator to GPU. For now it remains specific to the r,theta geometry.

Port the geometryRTheta interpolator to gpu

---

tests/geometryRTheta/advection_2d_rp/advection_all_tests.cpp
tests/geometryRTheta/advection_2d_rp/advection_selected_test.cpp
tests/geometryRTheta/advection_2d_rp/advection_simulation_utils.hpp
tests/geometryRTheta/advection_2d_rp/test_cases.hpp
tests/geometryRTheta/advection_field_rp/CMakeLists.txt
tests/geometryRTheta/advection_field_rp/advection_field_gtest.cpp
tests/geometryRTheta/advection_field_rp/test_cases_adv_field.hpp

Simplify r,theta advection tests to help with porting. Unnecessary inheritance is removed. This inheritance prevents the methods from being called from GPU. `KOKKOS_FUNCTION` tags are added to allow the test classes to be used on the GPU for tests

Prepare r,theta advection tests for GPU

---

tests/mapping/mapping_jacobian_matrix_coef.cpp
toolchains/a100.leonardo.spack/toolchain.cmake
toolchains/cicd_default_toolchain.cmake
toolchains/v100.persee/debug_toolchain.cmake
toolchains/v100.persee/environment.sh
toolchains/v100.persee/toolchain.cmake
toolchains/v100.ruche/toolchain.cmake

Update Persee environment with Kokkos 4.5.1, Kokkos Kernels 4.5.1 and Kokkos-fft 0.2.1

---

src/utils/non_uniform_interpolation_points.hpp

Use a better conditioned equation to calculate the step between grid points when creating uniform interpolation points. The uniform grid is compared to an input and the step is calculated from the input.

Improve rounding errors in uniform interpolation point initialisation

---

CMakeLists.txt
tests/geometryXVx/CMakeLists.txt

- set minimum supported to version 0.5.1, this brings the new DDC domains
- isolate the maxwellian tests to avoid failures, not clear yet why this makes it work. The issue is being tracked by https://github.com/CExA-project/ddc/issues/790

Update minimal version support of DDC

---

toolchains/mi250.hipcc.adastra.spack/toolchain.cmake

To totally fix ginkgo solver tests on AMD device, we have to deactivate OpenMp for the moment.

Deactivate OpenMP on adastra

---

src/data_types/indexed_tensor.hpp
src/data_types/tensor_index_tools.hpp
tests/data_types/CMakeLists.txt
tests/data_types/geometry_tensor.hpp
tests/data_types/static_assert_tests/CMakeLists.txt
tests/data_types/static_assert_tests/tensor_mul_3_indices.cpp
tests/data_types/static_assert_tests/tensor_mul_contra_contra.cpp
tests/data_types/static_assert_tests/tensor_mul_cov_cov.cpp
tests/data_types/static_assert_tests/tensor_mul_incompatible_index_set.cpp
tests/data_types/static_assert_tests/tensor_mul_multiple_types.cpp
tests/data_types/static_assert_tests/tensor_mul_wrong_index.cpp
tests/data_types/tensor.cpp

Improve `tensor_mul` static assertions. Add the missing static assert to verify if the `VectorIndexSet`s that are indicated with the same character id are compatible. Fixes #172.
Add tests to ensure static assertions are correctly raised

Improve `tensor_mul` static assertions

---

src/mapping/metric_tensor_evaluator.hpp
src/pde_solvers/polarpoissonlikesolver.hpp

Remove the misleading `to_covariant` method which does not fit with the naming conventions used in the rest of the code.

Remove the misleading `to_covariant` method

---

src/mpi_parallelisation/mpilayout.hpp
src/mpi_parallelisation/mpitransposealltoall.hpp

Use throw instead of assert for errors that can be caused by the user in the mpi_parallelization folder.

Use throw instead of assert where appropriate in MPI tools

---

src/geometryRTheta/advection_field/advection_field_rtheta.hpp
src/mapping/metric_tensor_evaluator.hpp
src/pde_solvers/polarpoissonlikesolver.hpp
tests/geometryRTheta/advection_field_rtheta/advection_field_gtest.cpp

The metric tensor should be expressed on the covariant basis by default, and its inverse on the contravariant basis

Express metric tensor on correct basis

---

src/io/input.hpp

Change the reading of the grid to read and write tor1 instead of grid_tor1.

Change input/output grid name for compatibility with netCDF

---

simulations/geometryXYVxVy/landau/params.yaml.hpp
src/mpi_parallelisation/mpilayout.hpp

Add a missing MPI error to ensure that a clean error message is raised if the number of grid points is not compatible with the number of MPI ranks.

Add missing MPI error

---

src/geometryRTheta/advection/bsl_advection_rtheta.hpp
src/geometryRTheta/advection/iadvection_rtheta.hpp
tests/geometryRTheta/advection_field_rtheta/advection_field_gtest.cpp

Complete the porting of `BslAdvectionRTheta` to GPU by porting the remaining `operator()` which acts on fields defined in r, theta coordinates.

Port (r,theta) BSL advection to GPU

---

.typos.toml

Updates the regexp in the `.typos.toml` files. 
With this update, the `inititialization' identifier in `ddc::some_function(initialization)` gets counted as an error by the spell checker.

Update typos config file

---

docs/mkdocs.yml

1. "Edit on github" linked to 404 on documentation webpage, has been now corrected
2. "mathjax" used the wrong library for displaying math font

mkdocs.yml updates

---

.github/workflows/cpu_tests.yml
.github/workflows/draft_flags.yml
src/geometryRTheta/advection/bsl_advection_rtheta.hpp
src/geometryRTheta/advection/iadvection_rtheta.hpp
src/geometryRTheta/advection_field/advection_field_rtheta.hpp
tests/geometryRTheta/advection_field_rtheta/advection_field_gtest.cpp
tests/geometryRTheta/advection_rtheta/advection_simulation_utils.hpp
tests/geometryRTheta/advection_rtheta/test_cases.hpp

This PR replaces the use of `CoordXY` with `DVector<X,Y>` to store the advection field in the Cartesian coordinate system. The advection field is not a coordinate so this type is not logical (it was used previously as Vector did not yet exist). Related to #39.

Store advection field in Vector not Coordinate

---

src/mapping/combined_mapping.hpp
src/mapping/inverse_jacobian_matrix.hpp
src/mapping/mapping_tools.hpp
src/mapping/metric_tensor_evaluator.hpp
src/pde_solvers/polarpoissonlikesolver.hpp
src/quadrature/volume_quadrature_nd.hpp
tests/mapping/mapping_jacobian.cpp
tests/mapping/mapping_jacobian_matrix_coef.cpp
tests/mapping/refined_discrete_mapping.cpp

The methods `has_2d_jacobian_v` and `has_2d_inv_jacobian_v` are overly complex. They were originally designed to allow the following:
```cpp
static_assert(mapping_detail::DefinesJacobian<Mapping, CoordinateType, !RaiseError>::value,
mapping_detail::DefinesJacobian<Mapping, CoordinateType, !RaiseError>::error_msg);
```
so the developer can quickly identify the problem with their implementation. However `static_assert` requires a literal string not just a compile-time string. This implementation therefore does not work. Further these methods were specific to the 2D case but we will soon add 3d mappings.
This PR therefore makes several improvements:
- Generalises the definition to work for ND (`has_2d_jacobian_v`-> `has_jacobian_v`, `has_2d_inv_jacobian_v`-> `has_inv_jacobian_v`)
- Removes …

Clean up mapping tools

---

src/mapping/barycentric_to_cartesian.hpp
src/mapping/cartesian_to_barycentric.hpp
src/mapping/cartesian_to_circular.hpp
src/mapping/combined_mapping.hpp
src/mapping/inverse_jacobian_matrix.hpp
src/mapping/mapping_tools.hpp
src/mapping/metric_tensor_evaluator.hpp
src/pde_solvers/polarpoissonlikesolver.hpp
src/quadrature/volume_quadrature_nd.hpp
tests/mapping/CMakeLists.txt
tests/mapping/mapping_jacobian.cpp
tests/mapping/mapping_jacobian_matrix_coef.cpp
tests/mapping/mapping_static_properties.cpp
tests/mapping/refined_discrete_mapping.cpp

Add a `mapping_static_properties.cpp` test for mappings to ensure that they correctly implement the expected properties. This shows that the jacobian methods for `CartesianToCircular` were incorrectly implemented in #213. The indices are fixed. Additionally the missing property is added to `BarycentricToCartesian` to show that it is an analytically invertible mapping.
To merge after #241

Fix bugs in the mappings

---

src/geometryXYVxVy/poisson/mpichargedensitycalculator.cpp

Correct me if I am wrong, I don't think we promise a that `rho_local` is ready after calling `m_local_charge_density_calculator`. This can lead to a race condition between an asynchronous backend and the MPI communication. I think we need to add a fence before `MPI_Allreduce`.
Note that it should not affect the benchmark results done with Kokkos Tools as regions will block.

Add a fence before communication

---

src/advection/ipolar_foot_finder.hpp
src/advection/spline_polar_foot_finder.hpp

Add batch dimensions to the polar spline foot finder. This will allow it to be used in high dimensional geometries without requiring a large loop around the GPU calls

Batch the polar spline foot finder

---

src/mapping/cartesian_to_circular.hpp
tests/mapping/CMakeLists.txt
tests/mapping/mapping_analytical_inverse.cpp
tests/mapping/mapping_jacobian.cpp
tests/mapping/mapping_jacobian_matrix_coef.cpp

Correct the equations for the cartesian to circular mapping and add tests for analytical inverses.
- All calculations associated with the Jacobian matrix were incorrect
- The theta component of the transformation was not provided in the expected range (0, 2pi)

Correct cartesian to circular equations

---

tests/geometryRTheta/polar_poisson/CMakeLists.txt

Increase timeout for polar Poisson tests. A larger timeout is needed when running with coverage flags as this slows the execution. Fixes #166

Increase timeout for polar Poisson tests

---

.github/actions/test_filter/action.yml
src/mapping/cartesian_to_circular.hpp
src/mapping/cartesian_to_czarny.hpp
src/mapping/circular_to_cartesian.hpp
src/mapping/czarny_to_cartesian.hpp
tests/geometryRTheta/advection_rtheta/advection_all_tests.cpp
tests/geometryRTheta/polar_poisson/polarpoissonfemsolver.cpp
tests/geometryRTheta/polar_poisson/test_cases.hpp

Add x0 and y0 parameters to circular and czarny coordinate change operators. Fixes #271

Add x0 and y0 parameters to circular and czarny coordinate change operators

---

src/geometryRTheta/poisson/iqnsolver.hpp
src/geometryRTheta/time_solver/bsl_predcorr.hpp
src/geometryRTheta/time_solver/bsl_predcorr_second_order_explicit.hpp
src/geometryRTheta/time_solver/bsl_predcorr_second_order_implicit.hpp
src/geometryRTheta/time_solver/itimesolver.hpp
tests/geometryRTheta/advection_field_rtheta/advection_field_gtest.cpp
tests/geometryRTheta/advection_rtheta/advection_simulation_utils.hpp

Rename `fdistribu` which indicates a distribution function (i.e. a function defined in phase space so on spatial **and** velocity dimensions) and `allfdistribu` which indicates a distribution function defined for all the different species to `density` in the r, theta geometry. This is done because the function of interest in the r, theta geometry has no dependency on velocity space or on species. Fixes #148

Rename fdistribu -> density in r,theta geometry

---

.github/actions/changed_files/action.yml
.github/actions/docker_update/action.yml
.github/actions/duplicate_check/action.yml
.github/actions/test_filter/action.yml
.github/workflows/cpu_tests.yml
.github/workflows/deploy.yml
.github/workflows/gpu_tests.yml
.github/workflows/static_analyses.yml
docker/gyselalibxx_env/Dockerfile

Before this PR the docker image was built whenever there is a push on the devel branch. This is problematic for multiple reasons:
- The CPU run on the devel branch does not wait for the docker file so it cannot use the changes
- The docker image is rebuilt even if it was not modified
- If we want to modify the `Dockerfile` we need to have 1 PR to update the file and a second to use the changes. This is awkward for testing.
This PR improves this situation by moving the `docker` job to `cpu_tests.yml`. It now triggers:
- on pushes to devel
- on a release of a new tag
- on pushes to a branch with a pull request
- on a workflow dispatch
It only recompiles if necessary, otherwise it simply runs build checks and retags the container.
The following CPU tests now depend on this runner. This …

Improve docker build trigger

---

tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp

Fix multipatch connectivity tests to make them less susceptible to rounding errors. Fixes #276

Fix test to handle rounding errors

---

src/mapping/circular_to_cartesian.hpp
src/mapping/mapping_tools.hpp

Allow overloaded functions in classes in `mapping/`. These classes are often tested with `is_mapping_v`, `has_jacobian_v` etc. These static checkers are designed to check if a specified method exists, but before this PR they did not handle overloaded methods correctly. No method was identified even if the required method existed. This PR fixes this by changing the implementation of `CheckClassAttributeExistence` to use the result type of the method (selected using the arguments) instead of the address of the method. Fixes #285.

Allow overloaded functions in coordinate convertor classes

---

src/data_types/tensor.hpp
src/mapping/identity_coordinate_change.hpp
src/utils/ddc_helper.hpp
tests/mapping/mapping_static_properties.cpp

Add an identity mapping. This is useful for testing vector expressions (which depend on a mapping) in a Cartesian geometry. Fixes #300

Add an identity mapping for testing

---

src/geometryRTheta/advection_field/advection_field_rtheta.hpp
src/mapping/cartesian_to_circular.hpp
src/mapping/cartesian_to_cylindrical.hpp
src/mapping/circular_to_cartesian.hpp
src/mapping/combined_mapping.hpp
src/mapping/cylindrical_to_cartesian.hpp
src/mapping/czarny_to_cartesian.hpp
src/mapping/discrete_to_cartesian.hpp
src/mapping/identity_coordinate_change.hpp
src/mapping/inverse_jacobian_matrix.hpp
src/mapping/mapping_tools.hpp
src/mapping/metric_tensor_evaluator.hpp
src/mapping/toroidal_to_cylindrical.hpp
src/mapping/vector_mapper.hpp
src/pde_solvers/polarpoissonlikesolver.hpp
src/quadrature/volume_quadrature_nd.hpp
tests/geometryRTheta/polar_poisson/test_cases.hpp
tests/mapping/mapping_jacobian.cpp
tests/mapping/mapping_jacobian_matrix_coef.cpp
tests/mapping/mapping_static_properties.cpp
tests/mapping/refined_discrete_mapping.cpp

In order to achieve #305 it is important to be able to deduce the coordinate system on which the Jacobian is calculated. To do this a `CoordJacobian` attribute is added to mappings which have a Jacobian.
**Commit Summary**
- Add `CoordJacobian` attribute to existing mappings
- Make `CoordJacobian` attribute compulsory for mappings which define a Jacobian.
- Remove `CoordinateType` template parameter from `has_jacobian_v` and `has_inv_jacobian_v`
- Update calls to `has_jacobian_v` and `has_inv_jacobian_v`
- `InverseJacobianMatrix` does not need a `PositionCoordinate` parameter
- Add missing static tests for `ToroidalToCylindrical`
- Ensure `ToroidalToCylindrical` is marked as having a singular inverse Jacobian
- Update default template parameter for `MetricTensorEvaluator`

Clean mapping interface

---

CHANGELOG.md
src/geometryXYVxVy/geometry/CMakeLists.txt
src/geometryXYVxVy/geometry/geometry.hpp
src/geometryXYVxVy/poisson/README.md
src/geometryXYVxVy/poisson/iqnsolver.hpp
src/geometryXYVxVy/poisson/nullqnsolver.cpp
src/geometryXYVxVy/poisson/nullqnsolver.hpp
src/geometryXYVxVy/poisson/qnsolver.cpp
src/geometryXYVxVy/poisson/qnsolver.hpp
src/geometryXYVxVy/time_integration/predcorr.cpp
src/geometryXYVxVy/vlasov/ivlasovsolver.hpp
src/geometryXYVxVy/vlasov/mpisplitvlasovsolver.cpp
src/geometryXYVxVy/vlasov/mpisplitvlasovsolver.hpp
src/geometryXYVxVy/vlasov/splitvlasovsolver.cpp
src/geometryXYVxVy/vlasov/splitvlasovsolver.hpp

Use a vector field for the electric field in the geometryXYVxVy. This removes the need for the constructor of `VectorField` which takes multiple `Field`s. This constructor is blocking for #322.
---

Use a vector field for the electric field in the geometryXYVxVy

---

CHANGELOG.md
tests/coord_transformations/jacobian.cpp
tests/coord_transformations/jacobian_matrix_coef.cpp
tests/coord_transformations/pseudo_cartesian_jacobian_matrix.cpp
tests/coord_transformations/refined_discrete_mapping.cpp
tests/coord_transformations/vector_basis_change.cpp
tests/geometryRTheta/advection_field_rtheta/advection_field_gtest.cpp
tests/geometryRTheta/advection_rtheta/advection_all_tests.cpp
tests/geometryRTheta/advection_rtheta/advection_selected_test.cpp
tests/geometryRTheta/polar_poisson/polarpoissonfemsolver.cpp
tests/geometryRTheta/quadrature/tests_L1_and_L2_norms.cpp
tests/geometryRTheta/spline_interpolator_rtheta/spline_interpolator_rtheta.cpp

Fix break points incorrectly labelled as knots. Fixes #69 
---

Stop naming 'break points' as 'knots'

---

CHANGELOG.md
toolchains/v100.ruche/environment.sh

The aim of this PR is to fix an environment issue encountered during Gysela-X tokamaxi simulations on Ruche. Indeed, running with more than one mpi process was leading to a segmentation fault because the version of MPI that was used was not GPU aware.
The swap command is used to ensure that the correct version of cuda and openmpi-cuda are used, and to avoid relying on automatically loaded versions of these modules.
---

Fix Ruche modules

---

CHANGELOG.md
src/matrix_tools/matrix_batch_csr.hpp
src/matrix_tools/matrix_utils.hpp
src/pde_solvers/polarpoissonlikesolver.hpp

Add the batch CSR convergence parameters to the constructor of the polar poisson solver so they can be modified in different ways for different simulations. Remove the line `Kokkos::deep_copy(m_x_init, x_init_host);` which prevents the previous solution being used as an initial guess for the convergence.
Fix typo `preconditionner`->`preconditioner`.
---

Improve matrix handling for polar poisson solver

---

src/interpolation/polar_splines/polar_bsplines.hpp
src/interpolation/polar_splines/polar_spline_evaluator.hpp

Evaluating polar bsplines involves 2 arrays to handle the singular bsplines and the tensor product bsplines. The method `eval_basis` returns an `Idx<BSplinesR, BSplinesTheta>` which identifies the smallest non-zero bsplines. However on devel this element can be a tensor bspline which doesn't exist in the polar bspline basis. As a result when calling `eval_basis` a small adjustment was required to ensure that fileds were not evaluated outside their domain. This PR fixes this logic issue. This simplifies the work on the polar Poisson solver.
---

Simplify polar bspline usage

---

CHANGELOG.md
src/geometryRTheta/time_solver/bsl_predcorr_second_order_explicit.hpp

Clean up bsl_predcorr.hpp in geometryRTheta ready for https://github.com/gyselax/gyselalibxx/pull/392 .
Improvements:
- Data allocations are now grouped to avoid reallocating data unnecessarily
- Data allocations have the suffix documented in the Coding standards (_alloc)
- Host variables have the suffix _host
- assign_vector_field_element is used to ensure equations will be simplified after https://github.com/gyselax/gyselalibxx/issues/322
- Unused variables are removed
---

Clean up `bsl_predcorr_second_order_explicit.hpp` in geometryRTheta

---

CHANGELOG.md
simulations/geometryRTheta/diocotron/diocotron.cpp
simulations/geometryRTheta/vortex_merger/vortex_merger.cpp

Copies of `phi_eq` in r,theta simulations (diocotron and vortex_merger) are coded incorrectly. They copy CPU to GPU instead of the inverse.
---

Fix bad copies in r,theta simulations

---

.github/workflows/install_tests.yml
CHANGELOG.md
toolchains/cpu.spack.gyselalibxx_env/gyselalibxx-env-0.23.1.yaml
toolchains/cpu.spack.gyselalibxx_env/prepare.sh
toolchains/cpu.spack.gyselalibxx_env/toolchain.cmake

The introduction of patched recipes allows to install more dependencies with Spack: Kokkos Kernels, kokkos-fft and Kokkos tools. This also allows to get rid of cloning recursively submodules.
The macOS runner has been set back to macos-14, the version that was previously tested, as the latest (macos-15) does not work yet for some reason.
---

Use patched recipes for the CPU Spack toolchain

---

CHANGELOG.md
toolchains/genoa.gcc.adastra.spack/environment.sh
toolchains/mi250.hipcc.adastra.spack/environment.sh

The Spack Kokkos Tools package does not expose the `lib` directory in the `LD_LIBRARY_PATH` making it non-trivial to use Kokkos Tools. The PR fixes this, further investigation should be made on the Kokkos team side.
---

Inject Kokkos Tools lib directory to LD_LIBRARY_PATH on Adastra

---

bin/ci_tools/check_for_memory_misuse.py

Report an error if a virtual function is callable from GPU. This would have caught the error seen in the Gysela-X repository.
---

Report an error if a virtual function is callable from GPU
