src/mapping/README.md

Add more formulae in the README.

Readme src/mapping

---

src/data_types/vector_field.hpp
src/data_types/vector_field_mem.hpp

Fix missing compilation error when manipulating VectorFields. Fixes #111

Improve compilation error output

---

src/mapping/metric_tensor.hpp
src/math_tools/math_tools.hpp
src/pde_solvers/polarpoissonlikesolver.hpp
tests/multipatch/geometries/5patches_figure_of_eight.hpp
tests/multipatch/geometries/9patches_2d_periodic_strips_uniform.hpp
tests/multipatch/geometries/physical_geometry.hpp

Part 1 of https://github.com/gyselax/gyselalibxx/issues/39

Use Vector type in Polar Poisson solver 

---

src/multipatch/data_types/multipatch_type.hpp

forgot a file with template type OT in [126](https://github.com/gyselax/gyselalibxx/pull/126)

Renamed OT into OtherType part 2

---

src/math_tools/l_norm_tools.hpp

Fix build error in norm_inf

---

.github/workflows/static_analyses.yml

Add post-process directory to list of spell-checked directories

---

toolchains/xeon.persee/debug_toolchain.cmake
toolchains/xeon.persee/environment.sh
toolchains/xeon.persee/release_toolchain.cmake
toolchains/xeon.persee/toolchain.cmake

Add an omp toolchain for Persee

---

src/math_tools/l_norm_tools.hpp

Correct the definition of norm_inf

---

src/data_types/indexed_tensor.hpp
src/data_types/tensor.hpp

This PR contains minor tensor improvements necessary for #127

Minor tensor improvements

---

ci_tools/markdown_linter.py

Remove magic numbers to improve the readability of the markdown linter test

Improve the readability of the markdown linter

---

src/utils/ddc_helper.hpp
tests/utils/test_ddcHelpers.cpp

Adding the `maximum_distance_between_adjacent_points` function in ddcHelper namespace

---

.gitlab-ci.yml
.typos.toml

Update the GitLab CI to fix the updated pylint command. Additionally add the new markdown linter and spell checker

Update GitLab CI

---

src/data_types/static_tensors.hpp
src/data_types/tensor_index_tools.hpp
src/utils/type_seq_tools.hpp
tests/data_types/geometry_tensor.hpp
tests/data_types/tensor.cpp

Add a Levi-Civita tensor type

---

src/math_tools/README.md
src/math_tools/central_fdm_partial_derivatives_with_boundary_values.hpp
tests/math_tools/test_partial_derivatives.cpp

Implement partial derivatives with boundary values

---

docs/first_steps/landau_damping_tutorial.md
docs/mkdocs.yml

Add a tutorial to the docs to talk users through the 1X-1V Landau damping code.

Add a Landau damping tutorial

---

src/mapping/README.md
src/mapping/metric_tensor_evaluator.hpp
src/mapping/toroidal_to_cylindrical.hpp
tests/mapping/geometry_mapping_tests.hpp
tests/mapping/mapping_jacobian.cpp
tests/mapping/metric_tensor_evaluator.cpp

Add a coordinate change operator to map from cylindrical coordinates to toroidal coordinates.

Add a ToroidalToCylindrical coordinate change operator

---

README.md
bin/ci_tools/markdown_linter.py
src/pde_solvers/polarpoissonlikesolver.hpp
tests/geometryRTheta/polar_poisson/CMakeLists.txt
tests/geometryRTheta/polar_poisson/test_poisson.py

Ensure coverage tests run correctly on devel branch by reducing the size of the Poisson test case. Add a badge to the README showing the test status

Ensure coverage tests run correctly on devel branch

---

docs/CONTRIBUTING.md
docs/mkdocs.yml

Add a CONTRIBUTING file to the documentation.

Add a CONTRIBUTING file to the docs

---

.gitmodules
CMakeLists.txt
simulations/geometryRTheta/diocotron/CMakeLists.txt
simulations/geometryRTheta/vortex_merger/CMakeLists.txt
src/geometryRTheta/initialisation/CMakeLists.txt
src/geometryRTheta/time_solver/CMakeLists.txt
tests/geometryRTheta/advection_field_rtheta/CMakeLists.txt
tests/geometryRTheta/advection_rtheta/CMakeLists.txt
toolchains/a100.leonardo.spack/spack.yaml
toolchains/mi250.hipcc.adastra.spack/environment.sh
toolchains/mi250.hipcc.adastra.spack/prepare.sh

Remove unused Eigen dependency

---

docs/first_steps/install.md

This PR aims at updating the git repository urls in `install.md`.

Update gyselalib URLs in installation guide

---

CHANGELOG.md

Update the CHANGELOG to show v0.1.0 and add the necessary sections for the next release.
---

Update CHANGELOG for new releases

---

docs/mkdocs.yml
docs/standards/coding_covariant_and_contravariant_tensors.md

Add a new page to the documentation detailing how the mathematical and physical conventions for tensors are implemented in the code.
---

Add documentation about tensor implementation

---

CHANGELOG.md
src/data_types/tensor.hpp
tests/coord_transformations/pseudo_cartesian_jacobian_matrix.cpp
tests/math_tools/test_gradient.cpp

- Remove unused member variable `Tensor::m_data_alloc` to fix `maybe-uninitialized` warning.
- Remove `R_cov::PERIODIC` and `Theta_cov::PERIODIC` and `GradientTestFunction::operator()` to fix other unused symbols.
---

Remove unused objects

---

CHANGELOG.md
src/geometryVparMu/initialisation/maxwellianequilibrium.cpp

Fix ignored m_magnetic_field
---

Fix ignored m_magnetic_field

---

CHANGELOG.md
src/matrix_tools/matrix_batch_csr.hpp
src/multipatch/data_types/multipatch_field.hpp
src/multipatch/data_types/multipatch_field_mem.hpp

Remove unnecessary std::move
closes #48 
---

Remove unnecessary std::move

---

.typos.toml
docs/mkdocs.yml
docs/troubleshooting/Common_compilation_problems.md
docs/troubleshooting/Debugging_workflow.md

Add an extra section about another compiler error in the developer FAQ. Add a section to the docs describing the best way to go about debugging issues.
---

Add debugging docs

---

.typos.toml

Add GAMs to dictionary

---

.github/actions/changed_files/action.yml

Fix docker issue

---

CHANGELOG.md
src/data_types/derivative_field_common.hpp
src/multipatch/data_types/types.hpp

Add types for MultipatchType in the `types.hpp` files: `DerivFieldOnPatch`  and `IdxRangeSliceOnPatch` types. 
Reorder and sort the aliases by device/host. 
Add/fix some documentation for the aliases. 
---

Add types for MultipatchType

---

CHANGELOG.md
src/multipatch/data_types/types.hpp
tests/multipatch/geometries/9patches_2d_periodic_strips.hpp
tests/multipatch/geometries/9patches_2d_periodic_strips_non_uniform.hpp

Currently,  the 9 patch periodic strip geometry exists only for uniform grids. 
Some test needs to have it on non-uniform grids. 
In this branch, a `9patches_2d_periodic_strips.hpp` files is created. It is inspired from the `3patches_2d_non_periodic.hpp` file to avoid duplication. `9patches_2d_periodic_strips_uniform.hpp`  is modified to rely on the new file. And `9patches_2d_periodic_strips_non_uniform.hpp`  is added. 
---

Add a 9 patch non uniform geometry for the periodic strips

---

CHANGELOG.md
toolchains/mi250.hipcc.adastra.spack/environment.sh
toolchains/mi250.hipcc.adastra.spack/gyselalibxx-spack-environment.yaml
toolchains/mi250.hipcc.adastra.spack/prepare.sh
toolchains/mi250.hipcc.adastra.spack/toolchain.cmake

- A new repository has been created to patch required recipes from v2025.07 to Spack v0.23
---

Adastra toolchain: install the Kokkos ecosystem with Spack

---

tests/advection/1d_advection_x.cpp
tests/advection/1d_advection_xvx.cpp
tests/advection/1d_advection_xyvxvy.cpp

Fix some pedantic warnings

---

docs/standards/coding_covariant_and_contravariant_tensors.md

Fix typos in docs. Fixes #412 
---

Fix typos in docs

---

CHANGELOG.md
toolchains/genoa.gcc.adastra.spack/environment.sh
toolchains/genoa.gcc.adastra.spack/gyselalibxx-spack-environment.yaml
toolchains/genoa.gcc.adastra.spack/prepare.sh
toolchains/genoa.gcc.adastra.spack/toolchain.cmake
toolchains/mi250.hipcc.adastra.spack/prepare.sh

Use Spack to install the Kokkos ecosystem in the GENOA Adastra toolchain

---

CHANGELOG.md
src/math_tools/curl.hpp
tests/math_tools/CMakeLists.txt
tests/math_tools/test_curl.cpp

Add a curl operator working on arbitrary geometry.
---

Add curl operator
